# Corona Virus (Covid-19) Data Processing 
## By: Charles MAWUSI

In [1]:
! pip3 install mysql-connector-python
import getpass
import mysql.connector 
from mysql.connector import Error 
import pandas as pd

Requirement already satisfied: mysql-connector-python in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (9.0.0)

In [2]:
## Using the defined Function to connect to server and database~COVID

def sql_db_connnection (name_database, name_host, name_user, user_password): # function to connect to mysql server 
    try:
        db_connection =mysql.connector.connect(
        database=name_database,
        host = name_host,
        user =name_user,
        password=user_password)
        
        if db_connection.is_connected():
            db_connection_info=db_connection.get_server_info()
            print("Connected succesfully to MySQL Server ", db_connection_info)
            
            cursor=db_connection.cursor()
            cursor.execute("SELECT database();") # shows the name of database
            record=cursor.fetchone()
            print("You are connnected to the Database:", record)
                 
    except Error as e:
        print("Error while connecting to", e)
    return db_connection

# I define the necessary info to connect to server

password=getpass.getpass("Enter password: " )
My_db_connection=sql_db_connnection("COVID", "localhost","root",password ) # my connected server

Enter password:  ········

Connected succesfully to MySQL Server  8.0.29
You are connnected to the Database: ('covid',)

In [7]:
# Define a function to read queries 

def read_queries(My_db_connection, query): 
    cursor=My_db_connection.cursor()
    result=None
    
    try:
        cursor.execute(query)
        result=cursor.fetchall() ## This execute your own querry  
        return result
        print("Query executed succesfully")    
        
    except Error as e:
        print("Error while connecting to", e)

In [9]:
## My Querries to check tables in database
connection =sql_db_connnection("COVID", "localhost","root",password )
query_tables="""SHOW TABLES;"""
myresults =read_queries(connection, query_tables )
for i in myresults:
    print(i)

Connected succesfully to MySQL Server  8.0.29
You are connnected to the Database: ('covid',)
('covid_data_deaths',)
('covid_data_mobility_trends',)
('covid_data_vaccinations',)

In [11]:
# select table 
query = """ SELECT * FROM COVID.covid_data_deaths
            LIMIT 20; 
            """

In [13]:
covid_data_deaths = read_queries(connection, query)
covid_deaths = pd.DataFrame(covid_data_deaths)
print(covid_deaths.columns.values)
covid_deaths

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,AFG,Asia,Afghanistan,2/24/2020,39835428,5,5,,,,...,,,,,,,,,,
1,AFG,Asia,Afghanistan,2/25/2020,39835428,5,0,,,,...,,,,,,,,,,
2,AFG,Asia,Afghanistan,2/26/2020,39835428,5,0,,,,...,,,,,,,,,,
3,AFG,Asia,Afghanistan,2/27/2020,39835428,5,0,,,,...,,,,,,,,,,
4,AFG,Asia,Afghanistan,2/28/2020,39835428,5,0,,,,...,,,,,,,,,,
5,AFG,Asia,Afghanistan,2/29/2020,39835428,5,0,0.714,,,...,0,,,,,,,,,
6,AFG,Asia,Afghanistan,03/01/2020,39835428,5,0,0.714,,,...,0,,,,,,,,,
7,AFG,Asia,Afghanistan,03/02/2020,39835428,5,0,0,,,...,0,,,,,,,,,
8,AFG,Asia,Afghanistan,03/03/2020,39835428,5,0,0,,,...,0,,,,,,,,,
9,AFG,Asia,Afghanistan,03/04/2020,39835428,5,0,0,,,...,0,,,,,,,,,
10,AFG,Asia,Afghanistan,03/05/2020,39835428,5,0,0,,,...,0,,,,,,,,,
11,AFG,Asia,Afghanistan,03/06/2020,39835428,5,0,0,,,...,0,,,,,,,,,
12,AFG,Asia,Afghanistan,03/07/2020,39835428,8,3,0.429,,,...,0,,,,,,,,,
13,AFG,Asia,Afghanistan,03/08/2020,39835428,8,0,0.429,,,...,0,,,,,,,,,
14,AFG,Asia,Afghanistan,03/09/2020,39835428,8,0,0.429,,,...,0,,,,,,,,,
15,AFG,Asia,Afghanistan,03/10/2020,39835428,8,0,0.429,,,...,0,,,,,,,,,
16,AFG,Asia,Afghanistan,03/11/2020,39835428,11,3,0.857,,,...,0,,,,,,,,,
17,AFG,Asia,Afghanistan,03/12/2020,39835428,11,0,0.857,,,...,0,,,,,,,,,
18,AFG,Asia,Afghanistan,3/13/2020,39835428,11,0,0.857,,,...,0,,,,,,,,,
19,AFG,Asia,Afghanistan,3/14/2020,39835428,14,3,0.857,,,...,0,,,,,,,,,

In [30]:
### importing colums as it is using sqlalchemy package 
from sqlalchemy import create_engine
query = "SELECT * FROM COVID.covid_data_deaths LIMIT 20; "
covid_deaths_data = pd.read_sql_query(query, con= My_db_connection)
covid_deaths_data

/var/folders/3b/jvvrp_7s1jz8p5_g9p9v60g00000gn/T/ipykernel_90896/2479919853.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  covid_deaths_data = pd.read_sql_query(query, con= My_db_connection)

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,2/24/2020,39835428,5,5,,,,...,,,,,,,,,,
1,AFG,Asia,Afghanistan,2/25/2020,39835428,5,0,,,,...,,,,,,,,,,
2,AFG,Asia,Afghanistan,2/26/2020,39835428,5,0,,,,...,,,,,,,,,,
3,AFG,Asia,Afghanistan,2/27/2020,39835428,5,0,,,,...,,,,,,,,,,
4,AFG,Asia,Afghanistan,2/28/2020,39835428,5,0,,,,...,,,,,,,,,,
5,AFG,Asia,Afghanistan,2/29/2020,39835428,5,0,0.714,,,...,0,,,,,,,,,
6,AFG,Asia,Afghanistan,03/01/2020,39835428,5,0,0.714,,,...,0,,,,,,,,,
7,AFG,Asia,Afghanistan,03/02/2020,39835428,5,0,0,,,...,0,,,,,,,,,
8,AFG,Asia,Afghanistan,03/03/2020,39835428,5,0,0,,,...,0,,,,,,,,,
9,AFG,Asia,Afghanistan,03/04/2020,39835428,5,0,0,,,...,0,,,,,,,,,
10,AFG,Asia,Afghanistan,03/05/2020,39835428,5,0,0,,,...,0,,,,,,,,,
11,AFG,Asia,Afghanistan,03/06/2020,39835428,5,0,0,,,...,0,,,,,,,,,
12,AFG,Asia,Afghanistan,03/07/2020,39835428,8,3,0.429,,,...,0,,,,,,,,,
13,AFG,Asia,Afghanistan,03/08/2020,39835428,8,0,0.429,,,...,0,,,,,,,,,
14,AFG,Asia,Afghanistan,03/09/2020,39835428,8,0,0.429,,,...,0,,,,,,,,,
15,AFG,Asia,Afghanistan,03/10/2020,39835428,8,0,0.429,,,...,0,,,,,,,,,
16,AFG,Asia,Afghanistan,03/11/2020,39835428,11,3,0.857,,,...,0,,,,,,,,,
17,AFG,Asia,Afghanistan,03/12/2020,39835428,11,0,0.857,,,...,0,,,,,,,,,
18,AFG,Asia,Afghanistan,3/13/2020,39835428,11,0,0.857,,,...,0,,,,,,,,,
19,AFG,Asia,Afghanistan,3/14/2020,39835428,14,3,0.857,,,...,0,,,,,,,,,

In [40]:
covid_deaths_data.columns

Index(['iso_code', 'continent', 'location', 'date', 'population',
       'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths',
       'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million'],
      dtype='object')